import numpy as np
import tensorflow as tf
import gensim.downloader as api

# Load the GloVe 300-dimensional model using gensim
print("Loading GloVe 300d model...")
glove_model = api.load("glove-wiki-gigaword-300")
embedding_size = 300
print("GloVe 300d model loaded.")

# Define a simple neural network model
def create_model(input_shape):
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(64, activation='relu', input_shape=input_shape),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dense(256, activation='relu'),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(input_shape[0], activation='linear')
    ])
    model.compile(optimizer='adam', loss='mse')  # Use string identifier 'mse'
    return model

# Initialize the model
model = create_model((embedding_size,))

# Training data
training_data = [
    {"input": "obliterate", "output": "destroy"},
    {"input": "annihilate", "output": "destroy"},
    {"input": "exterminate", "output": "kill"},
    {"input": "demolish", "output": "destroy"},
    {"input": "eradicate", "output": "remove"},
    {"input": "eliminate", "output": "remove"},
    {"input": "abolish", "output": "end"},
    {"input": "dissolve", "output": "end"},
    {"input": "nullify", "output": "cancel"},
    {"input": "transform", "output": "change"},
    {"input": "revolutionize", "output": "change"},
    {"input": "adjudicate", "output": "judge"},
    {"input": "arbitrate", "output": "judge"},
    {"input": "mediate", "output": "settle"},
    {"input": "negotiate", "output": "settle"},
    {"input": "facilitate", "output": "help"},
    {"input": "promulgate", "output": "issue"},
    {"input": "proclaim", "output": "announce"},
    {"input": "broadcast", "output": "announce"},
    {"input": "disseminate", "output": "spread"},
    {"input": "circulate", "output": "spread"},
    {"input": "elucidate", "output": "explain"},
    {"input": "illuminate", "output": "explain"},
    {"input": "expound", "output": "explain"},
    {"input": "endeavor", "output": "try"},
    {"input": "undertake", "output": "try"},
    {"input": "organize", "output": "arrange"},
    {"input": "orchestrate", "output": "arrange"},
    {"input": "coordinate", "output": "arrange"},
    {"input": "synthesize", "output": "combine"},
    {"input": "integrate", "output": "combine"},
    {"input": "amalgamate", "output": "combine"},
    {"input": "mitigate", "output": "reduce"},
    {"input": "diminish", "output": "reduce"},
    {"input": "lessen", "output": "reduce"},
    {"input": "alleviate", "output": "reduce"},
    {"input": "delineate", "output": "describe"},
    {"input": "illustrate", "output": "describe"},
    {"input": "articulate", "output": "speak"},
    {"input": "verbalize", "output": "speak"},
    {"input": "enunciate", "output": "say"},
    {"input": "rectify", "output": "correct"},
    {"input": "initiate", "output": "start"},
    {"input": "instigate", "output": "start"},
    {"input": "endorse", "output": "support"},
    {"input": "investigate", "output": "look"},
    {"input": "scrutinize", "output": "look"},
    {"input": "venture", "output": "go"},
    {"input": "ascend", "output": "climb"},
    {"input": "descend", "output": "climb"},
    {"input": "elevate", "output": "raise"},
    {"input": "consolidate", "output": "combine"},
    {"input": "fortify", "output": "strengthen"},
    {"input": "augment", "output": "increase"},
    {"input": "escalate", "output": "grow"},
    {"input": "embellish", "output": "adorn"},
    {"input": "accumulate", "output": "gather"},
    {"input": "aggregate", "output": "combine"},
    {"input": "segregate", "output": "separate"},
    {"input": "distinguish", "output": "differentiate"},
    {"input": "differentiate", "output": "distinguish"},
    {"input": "enumerate", "output": "count"},
    {"input": "safeguard", "output": "protect"},
    {"input": "insulate", "output": "protect"},
    {"input": "disclose", "output": "reveal"},
    {"input": "demonstrate", "output": "show"},
    {"input": "manifest", "output": "show"},
    {"input": "denote", "output": "mean"},
    {"input": "connote", "output": "mean"},
    {"input": "indicate", "output": "show"},
    {"input": "express", "output": "say"},
    {"input": "vocalize", "output": "speak"},
    {"input": "intonate", "output": "speak"},
    {"input": "utter", "output": "say"},
    {"input": "declare", "output": "announce"},
    {"input": "televise", "output": "show"},
    {"input": "radiate", "output": "spread"},
    {"input": "diffuse", "output": "spread"},
    {"input": "publish", "output": "print"},
    {"input": "imitate", "output": "copy"},
    {"input": "replicate", "output": "copy"},
    {"input": "fabricate", "output": "make"},
    {"input": "manufacture", "output": "make"},
    {"input": "construct", "output": "build"},
    {"input": "formulate", "output": "make"},
    {"input": "devise", "output": "plan"},
    {"input": "dispense", "output": "give"},
    {"input": "allocate", "output": "give"},
    {"input": "distribute", "output": "give"},
    {"input": "apportion", "output": "share"},
    {"input": "delegate", "output": "give"},
    {"input": "bestow", "output": "give"},
    {"input": "authorize", "output": "allow"},
    {"input": "sanction", "output": "approve"},
    {"input": "receive", "output": "get"},
    {"input": "assemble", "output": "gather"},
    {"input": "cluster", "output": "group"},
    {"input": "veil", "output": "hide"},
    {"input": "signify", "output": "mean"},
    {"input": "reproduce", "output": "copy"},
    {"input": "duplicate", "output": "copy"},
    {"input": "erect", "output": "build"},
    {"input": "procure", "output": "get"},
    {"input": "acknowledge", "output": "recognize"},
    {"input": "anticipate", "output": "expect"},
    {"input": "condense", "output": "shorten"},
    {"input": "expand", "output": "grow"},
    {"input": "illuminate", "output": "light"},
    {"input": "intensify", "output": "increase"},
    {"input": "magnify", "output": "enlarge"},
    {"input": "moderate", "output": "control"},
    {"input": "navigate", "output": "steer"},
    {"input": "neutralize", "output": "counteract"},
    {"input": "overhaul", "output": "revamp"},
    {"input": "postpone", "output": "delay"},
    {"input": "realign", "output": "adjust"},
    {"input": "refine", "output": "improve"},
    {"input": "reiterate", "output": "repeat"},
    {"input": "reinforce", "output": "strengthen"},
    {"input": "relinquish", "output": "give up"},
    {"input": "renovate", "output": "restore"},
    {"input": "saturate", "output": "soak"},
    {"input": "speculate", "output": "guess"},
    {"input": "streamline", "output": "simplify"},
    {"input": "substitute", "output": "replace"},
    {"input": "suppress", "output": "restrain"},
    {"input": "sustain", "output": "maintain"},
    {"input": "terminate", "output": "end"},
    {"input": "translate", "output": "interpret"},
    {"input": "validate", "output": "confirm"},
    {"input": "visualize", "output": "imagine"},
    {"input": "vindicate", "output": "justify"},
    {"input": "amend", "output": "correct"},
    {"input": "defend", "output": "protect"},
    {"input": "contribute", "output": "give"},
    {"input": "propose", "output": "suggest"},
    {"input": "dissipate", "output": "disperse"},
    {"input": "reclaim", "output": "recover"},
    {"input": "revive", "output": "restore"},
    {"input": "commemorate", "output": "honor"},
    {"input": "absorb", "output": "take in"},
    {"input": "elicit", "output": "bring out"},
    {"input": "enlist", "output": "recruit"},
    {"input": "endorse", "output": "support"},
    {"input": "excavate", "output": "dig"},
    {"input": "excite", "output": "thrill"},
    {"input": "ignite", "output": "light"},
    {"input": "initiate", "output": "begin"},
    {"input": "invoke", "output": "call upon"},
    {"input": "navigate", "output": "find your way"},
    {"input": "procure", "output": "get"},
    {"input": "stimulate", "output": "encourage"},
    {"input": "terminate", "output": "end"},
    {"input": "uphold", "output": "support"},
    {"input": "utilize", "output": "use"},
    {"input": "validate", "output": "confirm"},
    {"input": "withdraw", "output": "pull back"},
    {"input": "authenticate", "output": "verify"},
    {"input": "determine", "output": "decide"},
    {"input": "regulate", "output": "control"},
    {"input": "demonstrate", "output": "show"},
    {"input": "navigate", "output": "steer"},
    {"input": "illustrate", "output": "show"},
    {"input": "examine", "output": "inspect"},
    {"input": "scrutinize", "output": "examine"},
    {"input": "analyze", "output": "study"},
    {"input": "document", "output": "record"},
    {"input": "compile", "output": "gather"},
    {"input": "assemble", "output": "gather"},
    {"input": "generate", "output": "produce"},
    {"input": "synthesize", "output": "combine"},
    {"input": "formulate", "output": "develop"},
    {"input": "proclaim", "output": "announce"},
    {"input": "acquire", "output": "get"},
    {"input": "retain", "output": "keep"},
    {"input": "initiate", "output": "start"},
    {"input": "commence", "output": "start"},
    {"input": "culminate", "output": "end"},
    {"input": "finalize", "output": "complete"},
    {"input": "consume", "output": "eat"},
    {"input": "nourish", "output": "feed"},
    {"input": "support", "output": "help"},
    {"input": "sustain", "output": "maintain"},
    {"input": "facilitate", "output": "assist"},
    {"input": "aid", "output": "help"},
    {"input": "authorize", "output": "allow"},
    {"input": "permit", "output": "allow"},
    {"input": "license", "output": "allow"},
    {"input": "oversee", "output": "supervise"},
    {"input": "supervise", "output": "manage"},
    {"input": "administer", "output": "manage"},
    {"input": "guide", "output": "lead"},
    {"input": "direct", "output": "lead"},
    {"input": "coordinate", "output": "organize"},
    {"input": "orchestrate", "output": "organize"},
    {"input": "implement", "output": "carry out"},
    {"input": "enact", "output": "make law"},
    {"input": "legislate", "output": "make law"},
    {"input": "govern", "output": "rule"},
    {"input": "regulate", "output": "control"},
    {"input": "dictate", "output": "command"},
    {"input": "authorize", "output": "approve"},
    {"input": "approve", "output": "agree"},
    {"input": "ratify", "output": "confirm"},
    {"input": "validate", "output": "confirm"},
    {"input": "authenticate", "output": "verify"},
    {"input": "certify", "output": "verify"},
    {"input": "verify", "output": "check"},
    {"input": "endorse", "output": "support"},
    {"input": "sanction", "output": "approve"},
    {"input": "permit", "output": "allow"},
    {"input": "allow", "output": "let"},
    {"input": "grant", "output": "give"},
    {"input": "bestow", "output": "give"},
    {"input": "confer", "output": "give"},
    {"input": "donate", "output": "give"},
    {"input": "allocate", "output": "distribute"},
    {"input": "distribute", "output": "hand out"},
    {"input": "dispense", "output": "give"},
    {"input": "deploy", "output": "use"},
    {"input": "utilize", "output": "use"},
    {"input": "employ", "output": "use"},
    {"input": "adopt", "output": "take up"},
    {"input": "implement", "output": "apply"},
    {"input": "apply", "output": "use"},
    {"input": "invoke", "output": "call upon"},
    {"input": "administer", "output": "manage"},
    {"input": "govern", "output": "rule"},
    {"input": "command", "output": "lead"},
    {"input": "oversee", "output": "manage"},
    {"input": "direct", "output": "lead"},
    {"input": "control", "output": "regulate"},
    {"input": "supervise", "output": "manage"},
    {"input": "monitor", "output": "watch"},
    {"input": "observe", "output": "watch"},
    {"input": "evaluate", "output": "assess"},
    {"input": "assess", "output": "evaluate"},
    {"input": "judge", "output": "evaluate"},
    {"input": "critique", "output": "evaluate"},
    {"input": "analyze", "output": "examine"},
    {"input": "scrutinize", "output": "examine"},
    {"input": "inspect", "output": "examine"},
    {"input": "survey", "output": "examine"},
    {"input": "review", "output": "examine"},
    {"input": "examine", "output": "look at"},
    {"input": "consider", "output": "think about"},
    {"input": "contemplate", "output": "think about"},
    {"input": "ponder", "output": "think about"},
    {"input": "reflect", "output": "think"},
    {"input": "deliberate", "output": "consider"},
    {"input": "cogitate", "output": "think"},
    {"input": "muse", "output": "think"},
    {"input": "ruminate", "output": "think"},
    {"input": "meditate", "output": "think"},
    {"input": "speculate", "output": "think"},
    {"input": "theorize", "output": "think"},
    {"input": "hypothesize", "output": "guess"},
    {"input": "surmise", "output": "guess"},
    {"input": "conjecture", "output": "guess"},
    {"input": "prognosticate", "output": "predict"},
    {"input": "forecast", "output": "predict"},
    {"input": "foresee", "output": "predict"},
    {"input": "envision", "output": "see"},
    {"input": "foretell", "output": "predict"},
    {"input": "forewarn", "output": "warn"},
    {"input": "anticipate", "output": "expect"},
    {"input": "predict", "output": "forecast"},
    {"input": "prophesy", "output": "predict"},
    {"input": "divine", "output": "predict"},
    {"input": "speculate", "output": "guess"},
    {"input": "imagine", "output": "think"},
    {"input": "visualize", "output": "see"},
    {"input": "envision", "output": "see"},
    {"input": "fantasize", "output": "imagine"},
    {"input": "daydream", "output": "dream"},
    {"input": "hallucinate", "output": "imagine"},
    {"input": "wonder", "output": "think"},
    {"input": "ponder", "output": "think"},
    {"input": "consider", "output": "think"},
    {"input": "contemplate", "output": "think"},
    {"input": "reflect", "output": "think"},
    {"input": "meditate", "output": "think"},
    {"input": "muse", "output": "think"},
    {"input": "speculate", "output": "guess"},
    {"input": "hypothesize", "output": "guess"},
    {"input": "theorize", "output": "guess"},
    {"input": "surmise", "output": "guess"},
    {"input": "conjecture", "output": "guess"},
    {"input": "divine", "output": "guess"},
    {"input": "prognosticate", "output": "predict"},
    {"input": "forecast", "output": "predict"},
    {"input": "foresee", "output": "predict"},
    {"input": "envision", "output": "see"},
    {"input": "foretell", "output": "predict"},
    {"input": "forewarn", "output": "warn"},
    {"input": "anticipate", "output": "expect"},
    {"input": "prophesy", "output": "predict"},
    {"input": "divine", "output": "predict"},
    {"input": "speculate", "output": "guess"},
    {"input": "imagine", "output": "think"},
    {"input": "visualize", "output": "see"},
    {"input": "fantasize", "output": "imagine"},
    {"input": "daydream", "output": "dream"},
    {"input": "hallucinate", "output": "imagine"},
    {"input": "ponder", "output": "think"},
    {"input": "reflect", "output": "think"},
    {"input": "muse", "output": "think"},
    {"input": "meditate", "output": "think"},
    {"input": "speculate", "output": "guess"},
    {"input": "hypothesize", "output": "guess"},
    {"input": "theorize", "output": "guess"},
    {"input": "surmise", "output": "guess"},
    {"input": "conjecture", "output": "guess"},
    {"input": "divine", "output": "guess"},
    {"input": "prognosticate", "output": "predict"},
    {"input": "forecast", "output": "predict"},
    {"input": "foresee", "output": "predict"},
    {"input": "envision", "output": "see"},
    {"input": "foretell", "output": "predict"},
    {"input": "forewarn", "output": "warn"},
    {"input": "anticipate", "output": "expect"},
    {"input": "prophesy", "output": "predict"},
    {"input": "divine", "output": "predict"},
    {"input": "speculate", "output": "guess"},
    {"input": "imagine", "output": "think"},
    {"input": "visualize", "output": "see"},
    {"input": "fantasize", "output": "imagine"},
    {"input": "daydream", "output": "dream"},
    {"input": "hallucinate", "output": "imagine"},
    {"input": "ponder", "output": "think"},
    {"input": "reflect", "output": "think"},
    {"input": "muse", "output": "think"},
    {"input": "meditate", "output": "think"}
]

# Utility function to get embeddings from GloVe model
def get_embedding(word):
    if word in glove_model:
        return glove_model[word]
    else:
        return np.zeros(embedding_size)  # Return a zero vector if word is not found

# Convert the training data into numpy arrays using gensim embeddings
X_train = np.array([get_embedding(entry['input']) for entry in training_data])
Y_train = np.array([get_embedding(entry['output']) for entry in training_data])

# Train the model
model.fit(X_train, Y_train, epochs=1000, batch_size=4)

# Save the trained model to disk
model.save('verb_simplifier_model.keras')
print("Model saved to verb_simplifier_model.keras")
